version: 2.1
jobs:
  selenium-test:
    docker:
      - image: agajdosi/bk-tests:latest
    steps:
      - checkout
      - run:
          name: Run the tests
          command: BK_IS_DOCKER=True behave
      - store_artifacts:
          path: screenshots
          destination: screenshots

workflows:
  version: 2
  build_and_test:
    jobs:
      - selenium-test
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - selenium-test
